### ISSUE TITLE
media_check incorrectly reporting failure

### ISSUE THREAD

**Issue by Quitch** [JustinLove/ai_showdown#1]
I've updated to the latest master copy, but media_check reports:

Could not find AI files at the current media path.  Please edit `var media =` at
 the top of `Gruntfile.js`
C:/Program Files (x86)/Steam/SteamApps/common/Planetary Annihilation/media/

However, commands such as grunt copy:vanilla work fine, suggesting the path is correct.

**Comment by Quitch** [comment]
Verified this same behaviour occurs with the PTE branch.

**Comment by JustinLove** [comment]
Odd. Old ai_unit_map is still there on OS X but not on windows.  Changed the media check to ai_config.
