### ISSUE TITLE
Personalities adding an invalid field

### ISSUE THREAD

**Issue by Quitch** [JustinLove/ai_showdown#10]
Every personality has a name entry such as:

"name": "Vanilla - Hard"

To my knowledge this is not a valid field and should not be entered.

**Comment by Quitch** [comment]
Or is that because it's using an extended list format?

**Comment by JustinLove** [comment]
Stock ai.js has:

```
    _.forEach(result, function (element, key) {
        result[key]['name'] = key;
    });
```

By the time an append mod loads, the names are already in there, and we have to add them to stay in the same format.  Perhaps thats what you mean by "extended list" ?
