### ISSUE TITLE
New AI folder

### ISSUE THREAD

**Issue by Quitch** [JustinLove/ai_showdown#11]
TITANS adds a new folder called pa_ex1. Content for TITANS is loaded from here and added to content in pa. The AI is now split between the two and showdown needs to be able to support this split.

**Comment by JustinLove** [comment]
base_path needs to be any array of paths?

**Comment by Quitch** [comment]
Well the AI uses both, so all the vanilla support is in pa and expansion support is pa_ex1. Subfolder structure under both is the same.

For example the AI has its titan support in pa_ex1, but its building of a vehicle factory is still in pa.

So yes. If there are future expansions i expect something similar.

**Comment by Quitch** [comment]
Apologies, a little full of shit, it seems pa_ex1 overrides anything from pa it fines with matching name and folder structure. Still needs to support both to be able to build an AI with vanilla and expansion support, but you can do it with the tool with just a little extra work as it stands (running it, renaming, running again, merging the two)

**Comment by Quitch** [comment]
And mods can only override PA, so the results of multiple folders would need to be merged into one. As it stands pa_ex1 can safely override pa for AI.

**Comment by JustinLove** [comment]
base_path can be an array.

Did you have something further in mind for multiple content support?

**Comment by Quitch** [comment]
No, so long as it understands how to handle duplicate file names (pa_ex1 should take priority) then that's everything.

**Comment by JustinLove** [comment]
The base_path array is just successive copy, so if pa_ex1 is second it will take precedence.

**Comment by Quitch** [comment]
Best as I can figure base_path is actually a reference in the gruntfile to the path statements in the ai.json file. What I can't figure out is how an array should be formatted.

**Comment by JustinLove** [comment]
See ais.json.example

**Comment by Quitch** [comment]
Ah, I thought I had the latest files. This app continues to be a thing of beauty. Thanks!

**Comment by Quitch** [comment]
the ais.json is a little misleading it seems. The path appears to be used as to which set of files should override the other. If you put pa in the base path than Classic files will override their Titans copies, regardless of base_path order. Therefore the example should use pa_ex1 in the path, as I can't think of why you would ever want Classic override Titans files.
