### ISSUE TITLE
Fails on subdirectories

### ISSUE THREAD

**Issue by Quitch** [JustinLove/ai_showdown#3]
The AI supports parsing any and all files and folders within fbber_builds, factory_builds, platoon_builds, etc. However it appears the tool doesn't support some of these subfolders:

Running "builds" task
Warning: Unable to read "../server_mods/Queller-AI/pa/ai/platoon_builds/bronze"
file (Error code: EISDIR). Use --force to continue.

Aborted due to warnings.

**Comment by JustinLove** [comment]
Interesting.  Would it make sense to put each ai in its own directory?  I suppose something would still have to knock out vanilla.  Perhaps there should just be a null ai mod.

**Comment by Quitch** [comment]
You also need to include the following in the null files

{
   "build_list":[
   ]
}

Otherwise it doesn't work.

**Comment by JustinLove** [comment]
AI are now in subdirectories.  directory property replaces file_postfix.  directory: "" overwrites the vanilla files (assuming AI mod does; leaves relative paths unchanged)
