### ISSUE TITLE
Doesn't handle personality shadowing

### ISSUE THREAD

**Issue by Quitch** [JustinLove/ai_showdown#4]
It seems AI Showdown is setup to only handle mods which mirror the AI personalities i.e. how wondible does it. But if you shadow the personalities then they're not integrated into the final mod.

**Comment by JustinLove** [comment]
Please define your terms.  Personalities are a bit of a hack to avoid a full on js parser,  but I built what is there around s03g ai shadow.  I don't know what a mirror is.

**Comment by Quitch** [comment]
My understanding (based on PRoeleert's terminology) is that mirroring is when you define the scene in the modinfo file and store your files in the mod folder, while shadowing is when you create the full path in your mod's folder structure and don't define it as a scene in the modinfo file.

The eXodus mod mirrors, where as Alpha's Naval Trails shadows.

**Comment by JustinLove** [comment]
Okay, never had a word for that; I just think of them as scene mods.

What's the use case? Scene mods typically append functionality instead of replacing it, so there shouldn't be the "only one" issue with shadowing.  I see you've got a Queller personality mod, but that should just work as-is?

**Comment by Quitch** [comment]
Queller is now setup to only work with its own personalities. To avoid players breaking it it completely replaces the old personalities rather than appending to the list.

**Comment by JustinLove** [comment]
So what is the issue?  Do you want to play it against s03g's personalities?  Personality tag vanilla so they can fight?  Is multiple versions of Queller a problem?

**Comment by Quitch** [comment]
Currently it doesn't include Queller's personalities at all. I need it to merge those in with the vanilla ones, otherwise one of the AIs is playing with settings it's not supposed to, and in Queller's case it would just sit there.

**Comment by JustinLove** [comment]
Please pardon me for being so dense.

Right now all I can see on github is a client mod which appends personalities.  That should be pretty much unaffected by the server mod.

The server mod I can see on github loads no scene mods and doesn't have a ui directory to shadow with.  Are you doing personalities in the server mod in your local dev version?  Is the rule transformation process somehow stripping out the personality tag checks?  Does it need a facility to add personality tags checks in bulk?

**Comment by Quitch** [comment]
The Queller personalities - https://github.com/Quitch/Queller-AI-Personalities

Annnnnnnnnnnnnnnnnd I'm a dumbass. It's a client mod. What was I thinking?

I am shamed.

**Comment by Quitch** [comment]
Quitch is a dumbass.
