### ISSUE TITLE
Failure to detect media path

### ISSUE THREAD

**Issue by Quitch** [JustinLove/ai_showdown#7]
My copy of PA is found in a pretty standard path

C:/Program Files (x86)/Steam/SteamApps/common/Planetary Annihilation/media/

AI-showdown always fails to detect this and has to be configured manually.

**Comment by JustinLove** [comment]
I'll take another look for synchronous file apis.  Meanwhile, the PTE branch lets you set media path in the ai.json

**Comment by JustinLove** [comment]
Now checks multiple paths; not yet tested against most of them.
