### ISSUE TITLE
Default naming scheme creates undeletable folders

### ISSUE THREAD

**Issue by Quitch** [JustinLove/ai_showdown#9]
If you fail to match up your ais.json and gruntfile.js paths you're left with a mod folder name

com.wondible.pa.ai_showdown.

This cannot be deleted through any means I've found yet. Given that Windows clearly doesn't seem to like the dot at the end of the folder name might I suggest moving to another divider, such as a -, just in case of future issues.

This is assuming it's the . causing the issue.

**Comment by Quitch** [comment]
Even with the paths all aligned the identifier isn't being added. Here's a snapshot of my files:

  var identifier = 'com.wondible.pa.ai_showdown-' + ais.ais.map(function(ai) {return ai.rule_postfix}).join('')
  var modPath = (ais.server_mods || '../server_mods') + '/' + identifier + '/'

  "client_mods": "../mods",
  "server_mods": "../server_mods",

This results in the folder com.wondible.pa.ai_showdown- being created in server_mods.

**Comment by JustinLove** [comment]
Identifier building changed to filter and join, so it shouldn't generate trailing dots.

Added identifier (hard set) and base_identifier (extended with rule_prefix) to ais.json.
